# Generated by Django 6.0.6 on 2026-06-29 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Spsales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Voucher_no', models.CharField(max_length=50, null=True, unique=True, verbose_name='Voucher_no')),
                ('Vtype', models.CharField(max_length=50, verbose_name='Voucher Type')),
                ('invoice_no', models.CharField(blank=True, max_length=50, null=True)),
                ('Acno', models.CharField(blank=True, max_length=50, null=True, verbose_name='Account Name')),
                ('Trandate', models.DateField(blank=True, null=True, verbose_name='Transaction Date')),
                ('Recdate', models.DateField(blank=True, null=True, verbose_name='Rec Date')),
                ('Amount', models.IntegerField(blank=True, null=True, verbose_name='Amount')),
                ('Net_Amount', models.IntegerField(blank=True, null=True, verbose_name='Net Amount')),
                ('Mobile_no', models.CharField(blank=True, max_length=10, null=True, verbose_name='Mobile No')),
            ],
        ),
    ]
