# Generated by Django 6.0.6 on 2026-06-29 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vfp_offline_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spsales',
            name='Amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='spsales',
            name='Mobile_no',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Mobile No'),
        ),
        migrations.AlterField(
            model_name='spsales',
            name='Net_Amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Net Amount'),
        ),
    ]
